# Generated by Django 3.0.8 on 2020-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_listing_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('FN', 'Fashion'), ('TY', 'Toys'), ('AT', 'Antique'), ('CS', 'Computers'), ('AC', 'Accessories'), ('PC', 'Personal Care'), ('HD', 'Home Decor'), ('SP', 'Sports')], default='CS', max_length=2),
        ),
    ]
