# Generated by Django 3.0.8 on 2020-08-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200804_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creation_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
