# Generated by Django 3.0.8 on 2020-08-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200804_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentator',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
