# Generated by Django 3.0.8 on 2020-08-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200814_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
