# Generated by Django 3.0.8 on 2020-08-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200816_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('FN', 'Fashion'), ('TY', 'Toys'), ('AT', 'Antique'), ('CS', 'Computers'), ('AC', 'Accessories'), ('PC', 'Personal Care'), ('HD', 'Home Decor')], default='CS', max_length=2),
        ),
    ]
