# Generated by Django 3.0.8 on 2020-08-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200816_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_current_bid',
        ),
    ]
